export {default as CourseRegister} from 'components/CourseRegister'
export {default as Home} from 'components/Home'
export {default as Header}from 'components/Header'
export {default as Join}from 'components/Join'
export {default as Login}from 'components/Login'
export {default as Navi}from 'components/Navi'
export {default as NavigationForJavaScript}from 'components/NavigationForJavaScript'
export {default as OnlineProfile}from 'components/OnlineProfile'
export {default as SchoolStatus}from 'components/SchoolStatus'
